version: '3.8'

services:
  postgres:
    image: postgres
    container_name: demo-market-app-postgres
    environment:
      POSTGRES_DB: demo-market-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35432:5432"
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5